# Generated by Django 2.1.7 on 2019-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190708_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('опубликовано', 'Опубликовано')], default='draft', max_length=12, verbose_name='Статус'),
        ),
    ]
